channels:
  - bioconda
  - conda-forge
dependencies:
  - gh-scoped-creds
  - nbgitpuller
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-myst
  - jupyter-server-proxy
  - jupyter-book
  - jupyterhub-singleuser
  - numpy
  - matplotlib
  - ncbi-datasets-cli
  - pandas
  - fastqc
  - spades
  - trimmomatic
